carrier_article = ("Whether you’re looking to begin a new career or you want to change your current career, selecting "
                   "a future career can be a difficult decision. There’s a lot of points you need to consider in the "
                   "decision-making process, and while it’s vital to consider what interests you have, "
                   "it’s also important to look at how feasible career choices are to ensure they will provide you "
                   "with a comfortable life.\n\n"
                   "**Marketing Specialists**\n\n"
                   "There are so many forms of marketing, all of which are lucrative financially. Every type of "
                   "business and company you can think of will require a marketing team to help grow their business, "
                   "attract new customers, and make sales. Therefore, working in marketing can be an incredibly "
                   "versatile career, as you can end up working in lots of different industries. If you develop your "
                   "marketing skills, you can also work on a freelance basis quite efficiently, ensuring that no two "
                   "days are ever the same! Within the marketing department, there is a range of specialist roles "
                   "which you can follow to become a marketing specialist. You could try online marketing, "
                   "copywriting, or even become a Marketing Director.\n\n"
                   "**Medical Doctor**\n\n"
                   "Becoming a Medical Doctor can be an excellent career move, as there’s always a high demand for "
                   "trained Medical Doctors to join both the NHS and the private section in the UK. If you ready to "
                   "become a Doctor and pass all the exams and competency requirements, you will get a job as a "
                   "Medical Doctor in England.\n\nYou are working as a doctor with a high-paying salary, though you will "
                   "need to complete a medical degree first! While training at medical school can take about four to "
                   "seven years to become a fully-trained Doctor, it’s great to know that you have a guaranteed "
                   "career at the end of it all waiting for you!\n\n"
                   "**Orthodontist**\n\n"
                   "If you’re interested in pursuing a medical career, but you’re not sure about becoming a Doctor, "
                   "another smart choice could be to become an Orthodontist! Orthodontists work in dental medicine "
                   "and are specially trained to deal with tooth and jaw alignment. This means doing things like "
                   "assessing whether patients need braces as well as performing teeth straightening surgery! As an "
                   "Orthodontist, you will have to complete basically the same training as a Dentist, "
                   "and then complete further education to ensure you have the specialist knowledge required of an "
                   "Orthodontist.\n\n"
                   "**Geologist**\n\n"
                   "If you have a keen interest in science and nature, it could be incredibly financially rewarding "
                   "to train for a career as a Geologist! Geologists are specialist scientists involved in the study "
                   "of solid, liquid, and gaseous matter on Earth and other terrestrial planets. Working as a "
                   "Geologist may mean you spend a lot of time working outside, but you should also expect time in "
                   "the classroom, the lab, and offices. Working as a Geologist means you have the opportunity to "
                   "work for a range of different employers, including universities, government agencies, non-profit "
                   "organizations, or even mining companies.\n\n"
                   "**Investment Banker**\n\n"
                   "If you’re good with money and want to secure a large salary for yourself, you may consider a "
                   "career as an Investment Banker. As an Investment Banker, you will offer expert advice to "
                   "companies, institutions and governments on achieving their own financial goals and ensuring "
                   "financial security and success in the future! To get into investment banking, you typically need "
                   "a relevant degree and around four years of professional work experience to prove your skills. You "
                   "may also look at completing an investment banking internship to prove you’re serious about this "
                   "career choice. \n\n"
                   "**Aircraft Pilot**\n\n"
                   "While a degree is not required to become an Aircraft Pilot, you will need to complete a "
                   "significant amount of training before you can safely fly a plane. This will include getting your "
                   "pilot’s license, as well as passing a rigorous medical exam to ensure that you are fit to fly. "
                   "While a pilot’s life may seem exciting, you may be away from home for long periods, "
                   "so ensure this is the sort of career path you want to follow before you begin your intensive "
                   "training period. \n\n"
                   "**Advertising and Public Relations Director**\n\n"
                   "Working closely with the marketing team, an Advertising and Public Relations Director is another "
                   "exciting career path you could follow. Advertising and Public Relations Directors work on "
                   "creating a positive public image for their employer or clients. This means coordinating "
                   "advertising and public relations campaigns and working closely with the press to ensure high "
                   "levels of coverage. You can work as an Advertising and Public Relations Director in-house or as "
                   "part of an agency team, meaning you will be managing many clients simultaneously. You can also "
                   "work as an Advertising and Public Relations Director on a freelance level.\n\n"
                   "**Electrical Engineer**\n\n"
                   "If you love building things and have an analytical mind, then a career as an Electrical Engineer "
                   "could be perfect for you. Electrical Engineers design, develop, test and manage the manufacturing "
                   "of electrical equipment. This could mean working with everything from electric motors to power "
                   "generation equipment. To work as an Electrical Engineer, you will need a degree, "
                   "excellent communication skills, and the ability to demonstrate strong project management "
                   "skills.\n\n"
                   "**Higher Education Teachers**\n\n"
                   "While branching into teaching of any kind will open you up to a fantastic career and a "
                   "high-paying salary, if you’re looking for the best compensation possible, then you’ll want to "
                   "train to become a Higher Education Teacher. This means you will lecture students on a particular "
                   "subject in a university or higher education college. As a Higher Education Teacher, you will need "
                   "both extensive knowledge of the subject you are teaching and teaching techniques themselves.\n\n"
                   "**Psychiatrist**\n\n"
                   "A Psychiatrist is a medical doctor who specializes in mental health issues, including substance "
                   "abuse disorder. Unlike only training to become a counsellor or a psychologist, Psychiatrists must "
                   "train as medical doctors first and then choose to specialize in psychiatry as their field of "
                   "expertise. Holding sessions with clients and trying to help them work through their issues; "
                   "Psychiatrists can prescribe medication to their clients. Working as a Psychiatrist means you will "
                   "be able to work as part of a community health team, outpatient clinics, hospital wards, "
                   "or GP surgeries.\n\n")
