health_article = (
    "Local governments have had to take on a new responsibility; that of ensuring that people stay fit and healthy. Birmingham council is already hot on the case. For the past few years they have been encouraging local residents to enrol on the *Be active* scheme, which allows them to use local leisure services completely free of charge.\n\n"
    "Participants must register to obtain a membership card. They can then use the facilities in leisure centres across the city at certain times of the day."
    "29 leisure centres are signed up to the scheme. Each leisure centre must offer a minimum of one hour of swimming time and an hour of gym time to *Be Active* members. In reality, in some establishments in the more deprived areas, 70 percents of opening hours are reserved for Be Active members. Exercise classes and badminton courts are also made available on top of the standard facilities.\n\n"
    "*Be Active* classes are also being provided in schools and community centres. There are guided bike rides, and even proposals to roll out activities in public spaces such as rounders games in parks, and buggy pushes for new mothers.\n\n"
    "Since it was launched in 2008, a third of the local population, a total of 360,000 people, has signed up for the scheme. 60 percents of these are from minority groups, and the average age is 49, as opposed to 29, the figure for private gyms.\n\n"
    "The majority were not previously members of a sports club of any kind, half were overweight or obese, and a fifth considered themselves to be in poor health, indicating that the scheme is reaching the people who need it most. Research also shows that since the scheme was set up, there has been a rise in demand for information about reducing alcohol intake and quitting smoking.\n\n"
    "Statistics show that for every £1 spent on the *Be Active* scheme, £23 is saved in the health service. Sadly, the scheme has suffered from budget cuts, and lately it has had to reduce the hours available to members.\n\n"
    "Nonetheless, other councils are interested in the great strides made by Birmingham council, and officials from Birmingham have been holding workshops with representatives from other councils to spread the word about what can be achieved.\n\n"
)