american_edu_article = ("Math and reading scores for 13-year-olds have hit their lowest scores in decades.” When the "
                        "recent NAEP long-term trend results for 13-year-olds were published, the reactions were "
                        "predictable: short pieces in the nnational press and apologetics in education blogs. COVID-19, "
                        "we were told, was continuing to cast its long shadow. Despite nearly $200 billion in "
                        "emergency federal spending on K-12 schooling, students are doing worse than a decade ago, "
                        "and lower-performing students are today less capable of doing math than they were 35 years "
                        "ago. What is striking has been the pervasive weariness evident in the commentaries on the "
                        "results of the National Assessment of Educational Progress. The news was heralded as "
                        "“alarming,” “terrifying” and “tragic.”\n\nAs for responses? At the end of his piece on the "
                        "results, AEI’s Nat Malkus concludes that “nothing less than Herculean efforts will make up "
                        "for such shortfalls” — but on just what those efforts should be, he was silent. Writing for "
                        "The 74, political scientist Vladimir Kogan concludes that “the new federal data send a clear "
                        "message that we must do better” — but, once again, nothing about how. Other responses have "
                        "been predictable.\n\nIn her blog, Diane Ravitch wrote: “Will politicians whip up a panicked "
                        "response and demand more of what is already failing, like charter schools, vouchers, "
                        "high-stakes testing and Cybercharters? or [sic.] will they invest in reduced class sizes and "
                        "higher teacher pay?”\n\nHer response points to a familiar split in the education policy "
                        "community: On the one hand, the defenders of public education blame chronic underfunding of "
                        "schools and of teacher salaries in particular, and an overreliance on teaching to the test. "
                        "On the other, their conservative critics point to lack of school choice, poor teacher "
                        "preparation programs and (more recently) the woke invasion of classrooms. Both sides are "
                        "partially correct, of course: In multiple states, a heavy reliance on local property taxes to "
                        "pay for education creates regressive per-pupil funding, meaning that more dollars go to the "
                        "education of more affluent students. Teacher preparation still relies too much on textbook "
                        "theory instead of clinical practice (a vital switch the medical profession made a century "
                        "ago). Tests, especially in reading, are poorly designed (e.g., “Hamlet was confused because … "
                        "A, B, C or D — circle the right response”).\n\nToo many parents are stuck sending their "
                        "children to underperforming schools. But these are just symptoms. Factors beyond the "
                        "schoolhouse door – the legacy of race-based redlining, the underfunding of health care for "
                        "the worst off, the lack of support for child care and parental leave, and other social and "
                        "economic policies — remain hugely impactful. But inside the education system itself, "
                        "the fundamental cause of poor outcomes is that education policy leaders have eroded the "
                        "instructional core and designed our education system for failure. Pre-K is a wild West, "
                        "with the result that students enter kindergarten with large gaps in their readiness to learn. "
                        "Children aren’t seriously assessed until they are 8, by which time it’s too late for "
                        "sustained intervention — the gaps never close.\n\nMeanwhile, curricula, tests and teacher "
                        "education programs exist in deep silos, creating a fragmented system where teachers aren’t "
                        "trained to teach the materials their schools use and tests don’t test students’ mastery of "
                        "those materials (with a tiny exception in Louisiana). Almost uniquely among advanced "
                        "industrialized nations, U.S. school systems disconnect testing from student incentives. State "
                        "tests are used to evaluate schools but are often irrelevant to students: Only 11 states still "
                        "require high school exit exams for graduation, and there are often alternative pathways for "
                        "those who fail the test. We don’t link the results of high school exit exams to college "
                        "admissions — instead, using grade-point averages and tests like the ACT and SAT, "
                        "which are disconnected from course curricula.\n\nSpeaking of GPA, we have steadily inflated "
                        "grades at school and college: We simply call success what was once failure. We have also "
                        "created a preferential ranking of subjects. Student achievement in reading and math, and, "
                        "to a lesser extent, science, get all the attention, while students who are drawn to robotics, "
                        "graphic design, the arts, environmental science, etc., can’t take high school assessments "
                        "that count for entry into higher education.\n\nAt the same time, with a few shining "
                        "counterexamples, our career and technical learning options are a pale shadow of the world’s "
                        "best: While Switzerland designs exacting pathways from school to employment with options for "
                        "a return to higher education, America shunts millions of students into dead-end experiences, "
                        "where they discover that their CTE has failed to provide an employment-ready credential. "
                        "Many of these same students end up at community colleges with extraordinarily low graduation "
                        "rates. Perhaps in response to two decades of disappointing results, academic achievement "
                        "itself is increasingly out of fashion.\n\nCritical thinking, metacognition, grit and positive "
                        "mindset, and “21st century skills” are in — competence in mathematics, not so much. It seems "
                        "to have escaped us that students cannot think critically about nothing in particular; mastery "
                        "of content is a prerequisite. The turn away from academics is rocket-propelled by a genuine "
                        "problem. American teenagers stare at social media on a screen almost nine hours every day, "
                        "with one result being surging loneliness and depression. Many American school systems have "
                        "reacted by putting social and emotional learning at the top of the agenda. Few would argue "
                        "that students shouldn’t be given effective support — putting mental health counselors in "
                        "large high schools, for example, makes sense.\n\nBut the pretense that there is a new science of "
                        "SEL is largely pablum. When you chase it to ground, what it means is that teachers should "
                        "encourage, not discourage, students: a poor test result calls for more effort, "
                        "not the conclusion that the child is bad at math. Such wisdom has been available for 2,"
                        "000 years. To top it all off, the American K-12 education system spends at least $30 billon "
                        "per year on educational technology with essentially nothing to show for it.\n\n As it was for "
                        "the introduction of radio, then TV, then computers, so it is likely to be for artificial "
                        "intelligence — the latest great hope to circumvent and supplant effective, inspiring teaching "
                        "of children by a human being. As we have sown, so shall we reap. The unique sense of "
                        "achievement that a student experiences when she or he masters a rigorous skill, "
                        "digs into deep knowledge, creates a piece of writing or art, completes a challenging science "
                        "assignment or piece of music — this is all being washed away. We are tired of bad news, "
                        "and our instinct is now to punish, or at least ignore, the messenger. But our students are "
                        "desperately the worse for the mess we have made of their schooling.")

transform_edu_article = ("Every single day, the challenges of global education become more daunting and more "
                         "urgent. Just a few days ago on June 21, the United Nations reported that as many as 222 "
                         "million school-aged children impacted by crisis require urgent educational support—this "
                         "number is three times the estimates from 2016.\n\n Furthermore, as currently reported by "
                         "the World Bank and UNICEF, the portion of 10-year-olds in low- and middle-income "
                         "countries during the pandemic who could not read a simple story is estimated to have "
                         "grown from about 50 percent to over 70 percent today. The poorest children and those "
                         "living in remote regions have been hit the hardest. We are at a critical inflection "
                         "point with hundreds of millions of children likely to miss out on a quality education "
                         "in the very moment where we have to confront climate change, increasing conflict, "
                         "and renewed pandemic risks. Alarm bells are being sounded and the United Nations "
                         "secretary general has invited political leaders, policymakers, youth, "
                         "and all stakeholders to join him at the Transforming Education Summit (TES) in New York "
                         "in September 2022 to make commitments that will transform education.\n\nWe agree that "
                         "something different and transformational needs to happen now. But what does "
                         "transformation mean, anyway?\n\nHere we share a condensed version of our perspective on "
                         "how policymakers can better understand what it means and most importantly get started "
                         "with making significant commitments for action. We don’t have the final answers, "
                         "but we want to share the perspective of a global think tank that has studied the "
                         "development of education systems over the past 100 years and a national government from "
                         "a low-income country in the midst of an education transformation.\n\nAt its core, "
                         "system transformation must entail a fresh review of the goals of our education systems. "
                         "There must be a frank assessment—are the goals meeting the moment that we are in and "
                         "are they owned broadly across society? If the answer is “no,” then transformation means "
                         "repositioning all components of the education system to coherently contribute to a new, "
                         "shared purpose.\n\nWe hope that countries and local stakeholders can use these insights to "
                         "take the [education] transformation journey forward wherever they are. We propose three "
                         "steps centered on purpose, pedagogy, and position that embed a participatory, "
                         "inclusive approach as the key to successful transformation.\n\nStep 1: Start with purpose "
                         "Education leaders, families, teachers, and students can have very different "
                         "expectations about the purpose of their education system. Without a broadly shared "
                         "vision in and outside of the education system, any attempt at transformation will have "
                         "a slim chance of success. When education leaders do take the time to have meaningful "
                         "conversations with diverse stakeholders about the goals of education, it can help pave "
                         "the way for a broadly shared vision. Such a shared vision has played a key role in "
                         "successful reforms in Portugal, Finland, and Canada.\n\nIn Sierra Leone, the most recent "
                         "education sector plan was developed after careful and thorough consultations with a "
                         "wide group of stakeholders. In addition to the national and local government, "
                         "partner countries and civil society organizations, the government has made a point of "
                         "consulting previously excluded groups like the bike riders union, the market women’s "
                         "associations, and traditional and religious leaders across the country. Given the deep "
                         "inequality in students’ learning in Sierra Leone which was highlighted by all "
                         "stakeholders, the education sector plan and strategy prioritize foundational learning "
                         "not as an end goal but as the floor to give every child a chance for longer-term "
                         "educational success. And the country now puts the children who are currently learning "
                         "the least at the front of its efforts thanks to its Policy on Radical Inclusion in "
                         "Schools.\n\nStep 2: (Re)design the pedagogical core The second step is to (re)design "
                         "teaching and learning experiences to ensure students achieve the system’s stated goals. "
                         "Unfortunately, redesigning education systems often results in limited results for "
                         "children’s learning and development. We need to focus more on what students are "
                         "expected to learn—not just how that content is delivered—and we need to pay special "
                         "attention to those who are learning the least.\n\nSome of the most promising results that "
                         "take this approach to heart in recent years come from a practice called Teaching at the "
                         "Right Level. Grouping children by ability level and conducting interactive learning "
                         "activities for a period of time each day is at the core of this methodology. Real-time "
                         "assessments provide data needed to move students on to higher level groups as they "
                         "master skills. The approach is most effective for education systems that have large "
                         "numbers of students failing to master literacy and numeracy by the end of primary "
                         "school and where the default teaching approach is whole group instruction, "
                         "even with very large class sizes.\n\nIn Sierra Leone, the country has joined the first "
                         "cohort of World Bank Accelerator Program countries to explicitly change its pedagogical "
                         "core to support foundational learning. In addition, the country has launched the Sierra "
                         "Leone Education Innovation Challenge to generate key evidence on what can help improve "
                         "learning outcomes. Several of the service providers are adopting Teaching at the Right "
                         "Level to improve learning outcomes. Initial signs are positive for our learning "
                         "outcomes, as even with COVID-19 disruptions, we do not have major learning losses even "
                         "if no gains were made.\n\nStep 3: Position and align system components Next, the system "
                         "must be positioned to support the pedagogical core across the following six components: "
                         "(1) Curriculum, (2) Human resources, (3) Data and assessment, (4) Governance, "
                         "(5) Funding, and (6) Engagement of “winners” and “losers” in the alignment process. In "
                         "Sierra Leone, the government has recently updated the preprimary, basic, "
                         "senior secondary, civic, and technical and vocational education and training (TVET) "
                         "curricula. In addition, the country has paid special attention to using data to support "
                         "the realignment behind the updated pedagogical core while investing in teacher "
                         "training at all levels.\n\nBefore 2018, Sierra Leone had little detailed information about "
                         "who its education system served and who it left out. Data collection had used "
                         "paper-based questionnaires, and, as a result, data were often lagging by up to a year "
                         "and scattered across multiple government departments. Sierra Leone set about digitizing "
                         "its annual school census and cut the data collection time to 10 weeks. By also "
                         "carefully updating the questions asked, Sierra Leone shed light on who was left out of "
                         "the system. Now the Annual School Census is both gender-disaggregated and asks about "
                         "the disability status of the students and the accessibility of the classrooms. "
                         "Moreover, the Ministry digitized and linked education data going all the way back to "
                         "2015. This gave the Ministry a data-driven starting point for addressing disparities "
                         "within the education system, and it remains a crucial component supporting its goals of "
                         "developing a more inclusive system, including for pregnant girls and children with "
                         "disabilities.\n\nWhat now? We believe that there is much to learn from history and "
                         "solutions currently being implemented around the world to help us. As Minister Sengeh’s "
                         "Co-Chair of the TES Advisory Committee and the Deputy Secretary General Amina Mohamed "
                         "recently said: “This is not ‘t’ for tweaking. This is ‘T’ for Transformation.” We hope "
                         "that countries and local stakeholders can use these insights to take the transformation "
                         "journey forward wherever they are—and for those that are further along on the path, "
                         "please do share your experiences with us and the world. We look forward to adding your "
                         "learnings and lessons to the collective effort to achieve Sustainable Development Goal "
                         "4—quality education for all.")

uk_edu_article = ("British education is admired and respected all across the globe. Centuries of experience and "
                  "innovative approaches to teaching make the UK stand out from other English-speaking countries. "
                  "That is probably why Britain is known as the second most popular country for international "
                  "students. Here are some facts that will help you to see what makes education in the UK one of the "
                  "best in the world.\n\n"
                  "**Facts for International Students**\n\n"
                  "1. As the UK is considered to be the heart of the English-speaking world, there is a perfect "
                  "English language support provided to international students to help them complete their courses "
                  "successfully.\n\n"
                  "2. In comparison to other countries, getting a degree in the UK usually takes less time allowing "
                  "you to save money. Generally, it takes 3 years to complete Bachelor’s degree and Master’s degree "
                  "course usually takes a year to complete.\n\n"
                  "3. Students in the UK have a great possibility to become a part of the working world while they "
                  "study. It is allowed to work up to 20 hours per week during an academic year and full-time during "
                  "vacations.\n\n"
                  "4. The UK provides international students with a lot of opportunities and benefits, including "
                  "discounts on stationery, books, entertainment, and travel. So education in the UK is not just "
                  "about the high level of teaching, it is about fun and entertainment as well.\n\n"
                  "5. There is a great number of scholarships in the UK available both for local and international "
                  "students, as well as postgraduate and undergraduate ones.\n\n"
                  "6. International students who stay in the UK for more than 6 months can enjoy the benefit of free "
                  "subsidized healthcare provided by the National Health Service.\n\n"
                  "7. The UK provides students with the ability to choose from four culturally and geographically "
                  "diverse countries. These are England, Wales, Scotland or Northern Ireland.\n\n"

                  "**Interesting Facts about Schools**\n\n"
                  "1. The first in the UK and the oldest continuously operating school in the world, The King’s "
                  "School in Canterbury, was founded in 597 AD. There have been various sorts of schools in England, "
                  "Scotland, Ireland and Wales for many centuries. Nevertheless, until the Education Act of 1944, "
                  "secondary education in the UK was not free.\n\n"
                  "2. One of the most interesting facts about schools in the UK is that some of them open and close "
                  "several times during their history. For example, there is a local school situated on Caldey Island "
                  "that saw a number of openings and closures during its long history because of rises and falls in "
                  "the number of children on the island.\n\n"
                  "3. The Nottingham Academy that was created from the merger of three schools is considered to be "
                  "the biggest one in the UK, as well as the biggest one in Europe. The population of the Nottingham "
                  "Academy is 3,600 pupils, about 200 teachers and more than 100 administrators and assistants. "
                  "Nevertheless, it is not the biggest school in the world. There is a City Montessori school in "
                  "Lucknow, in India that has a population of more than 32,000 pupils.\n\n"
                  "4. The smallest school in the UK has a population of fewer than half-dozen of children. The school "
                  "is Holy Island Church of England First School. It proves that any place where people gather to "
                  "learn together can be called a school.\n\n"
                  "5. The best school in the UK, the school with the greatest exam results, is Chelmsford county high "
                  "school. Nevertheless, it is hard to judge the quality of the school as any school can be rated in "
                  "accordance with different features, such as best classrooms, best teachers or best lunches. "
                  "Perhaps, you can say that the best school is Springfield Elementary or Bikini Bottom Elementary. "
                  "Just because these schools are not real, does not mean they are bad.\n\n"
                  "6. There are many students who will say that their school is the worst. Those students do not have "
                  "a clue about Victorian schools that existed in the UK. How about classrooms divided by curtains "
                  "and 100 students in a class? Or how about no chance to look at the window and to daydream for a "
                  "couple of minutes because windows are built high up in the walls? Your school is not as bad as you "
                  "think it is.\n\n"
                  "**Fun Facts about Universities**\n\n"
                  "1. Researchers at Warwick Manufacturing Group at the University of Warwick showed the world how to "
                  "go green in the weirdest way. They designed and developed a car that was made of potatoes, "
                  "steered by carrots and used chocolate instead of gasoline. Yes, it was exactly the edible F3 "
                  "racing car that showed that education in the UK can be really funny and genius.\n\n"
                  "2. The University of York has a population of more than 15, 000 students. Also, the university has "
                  "quite a massive population of ducks. There are approximately 14 ducks for every 1/4 of an acre on "
                  "the campus. If you think it is cute, do not jump to conclusions. Some ducks are quite aggressive "
                  "and there is one red and a yellow head duck named ‘Beer Monster’ because of its rude behavior.\n\n"
                  "3. One of the best examples of the fight against the system belongs to Lord Byron who studied at "
                  "Cambridge University in the 19th century. He dreamed of a pet dog and there was one he tried to "
                  "keep during his study but unfortunately, he was made to get rid of it. So instead of a pet dog, "
                  "Lord Byron decided to pet a bear. There was no legal argument against petting a bear.\n\n"
                  "4. The UK’s oldest student newspaper started in 1887 by the author of Treasure Island and The "
                  "Strange Case of Jekyll and Hyde, Robert Louis Stevenson, who studied at the University of "
                  "Edinburgh.\n\n"
                  "5. There is a university in the UK where you will be able to find a patch of grass full of "
                  "tombstones that stand"
                  "right next to the admin block. Previously, there was a church where Coventry University is now "
                  "situated, so the patch is classed as sanctified ground and that is why tombstones cannot be "
                  "removed.\n\n"
                  )
